console.log(Math);
console.log(Math.abs(-4));
console.log(Math.round(4.6));
console.log(Math.floor(4.9));
console.log(Math.ceil(4.1));
console.log(Math.min(4,6,2,7));
console.log(Math.max(4,6,2,7));


console.log(Math.random());// value generated by random method is always lies between 0 to 1
console.log(Math.random(Math.random()*10)+1);

const min = 10
const max = 20

console.log(Math.floor(Math.random()*(max-min))+min);